#!/bin/bash

# This file is part of the wiFred wireless model railroading throttle project
# Copyright (C) 2018  Heiko Rosemann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
#
# This file is a shell script defining the current firmware version from the
# compile date and git hash. Make it executeable and add the following line 
# to your platform.local.txt:
# recipe.hooks.sketch.prebuild.0.pattern={build.source.path}/make-git-version "{build.source.path}" "{build.path}"
#
# This file itself will not be compiled. Include gitVersion.h to have REV defined.
# Do not forget to make this file executeable


# Go to the source directory.
[ -n "$1" ] && cd "$1" || exit 1

# Build a version string with git.
version=$(date -I)$(git log -n 1 --pretty=format:%h 2> /dev/null)

# Save this in git_version.h.
echo "#define REV \"$version\"" > $2/sketch/gitVersion.h
