= Hintergrund und Geschichte der wiFred-Entwicklung
Heiko Rosemann
0.4, 6-30-2023: Aufteilung auf mehrere Dokumente - automatisch übersetzt von Axel Thobaben unter Verwendung von Microsoft Edge
:description: wiFred development, background, similar projects
:url-repo: https://github.com/newHeiko/wiFred
:icons: image
:iconsdir: images/icons/
:imagesdir: images/
:lang: de
:toc:


Zum Zeitpunkt des Schreibens dieses Dokuments hat <<JMRI>> bereits eine lange Erfolgsbilanz bei der Bereitstellung eines Servers für die Verwendung von Smartphones als drahtlose Modelleisenbahn-Handregler, zusammen mit Apps wie <<wiThrottleApp>>footnote:[wiThrottle ist auch der Name, den JMRI für das Protokoll und den Server verwendet.] und <<EngineDriver>>. Dieser Server ermöglicht WLAN-Handregler, um Loks jedes Modelleisenbahnlayout zu steuern, zu dem JMRI eine Verbindung aufbauen kann <<jmrihardwaresupport>>. Darüber hinaus bieten <<Digitrax>> und <<MRC>> spezifische Hardwarelösungen an, um die Verbindung der oben genannten Smartphone-Apps mit ihren DCC-Systemen über ein WLAN-Netzwerk zu ermöglichen.

Der <<Fremo>> ist ein europäischer modularer Modelleisenbahnclub, dessen einzigartige Anforderungen an seine DCC-Handregler zur Schaffung der Handregler <<FRED>> und <<FREDI>> führten - eine Reihe von LocoNet-Handregler, die als Hobbyprojekte mit großen Stückzahlen im Umlauf begannen, später von <<Uhlenbrock>> kommerziell erhältlich waren.

=== Spezifikation Wunschliste

Bei modularen Eisenbahnveranstaltungen, insbesondere der Fremo-americaN-Gruppe, haben mehrere Personen die Smartphone-Handregler-Apps ausprobiert und festgestellt, dass ihnen ein schönes, haptisches Feedback fehlt. Aber die Idee der drahtlosen Steuerung ohne Bindung an einen bestimmten Anbieter und deren notwendigerweise teure Ausrüstung fand große Zustimmung. Also wurde eine Wunschliste zusammengestellt, um die Anforderungen an eine drahtlose Drehregler zu definieren:

- Gleicher Formfaktor wie der <<FRED>> mit ähnlicher Bedienung

- Möglichkeit, mindestens zwei, bessere vier Lokomotiven für Doppel-/Dreifachtraktion zu steuern (ähnlich dem Duo-FREDI)

- Akkulaufzeit von mindestens sechs Stunden

- Austauschbare Batterien, so dass, wenn der Akku leer ist, sie schnell gegen ein geladenes Set oder billige Primärzellen ausgetauscht werden können

- Einfache Konfiguration, aber nicht zu einfach, um zu verhindern, dass Bediener versehentlich andere Lokomotiven auswählen

- So wenig Änderung am bestehenden Fremo Loconet Netzwerk wie möglich

- Verwendung des wiThrottle-Protokolls, so dass davon ausgegangen werden kann, dass die Serverseite der Kommunikation funktioniert und nicht ebenso entwickelt werden muss

=== Entwicklungsgeschichte

Die ersten Prototypen des wiFred wurden so gebaut, dass sie mit zwei AA-Zellen betrieben werden, entweder Batterien oder wiederaufladbaren NiMH-Akkus. Wie in <<oldThrottle>> beschrieben, erforderte dies einige spezielle Anpassungen des Gehäuses, um alle Komponenten unterzupassen. Schon damals zeigte die Erfahrung mit den Prototypen, dass die Batteriefachabdeckung nicht wirklich passte und beim Versuch, das Batteriefach zu öffnen und zu schließen, leicht kaputt ging.

So wurden die nächsten Versionen um einen integrierte Lithiumakku herum entwickelt, womit die Option verloren ging, leere Batterien einfach auszutauschen. Dafür war die Laufzeit länger und die Elektronik passte richtig in das Gehäuse. Das Aufladen der zweiten Generation erfolgt über einen Micro-USB-Anschluss, so dass eine Powerbank die Laufzeit des Geräts verlängern kann, wenn der interne Akku erschöpft ist. Außerdem fungieren die Lokauswahlschalter mehr als ein Netzschalter als bei den ersten Prototypen und reduzieren den Stromverbrauch auf einen vernachlässigbaren Betrag, wenn alle Loks deaktiviert sind.

Der neueste Prototyp wird von zwei Prozessoren auf einen einzigen, neuen ESP32-S2-Prozessor umgestellt, was Platz spart, die Anzahl der Komponenten reduziert, alle SMD-Komponenten auf einer Seite der Leiterplatte platziert und einen direkten USB-Firmware-Download ermöglicht. Es wird keine neuen Funktionen gegenüber den früheren LiPo-Akkuversionen enthalten, aber hauptsächlich für den Bastler einfacher zu bauen sein.

=== Drahtlose Uhr

Während der Entwicklung dieses wiFred kam in der americaN-Gruppe der Fremo ein weiteres Thema auf, nämlich drahtlose Uhren mit einstellbarer Taktrate für Timetable & Trainorder-Betrieb. Dies führte zur Ausgliederung des <<wiClock>>-Projekts.

[bibliography]
== Quellen

- [[[github,Github repository für wiFred]]] newHeiko/wiFred: wiThrottle-compatible hardware controller, https://github.com/newHeiko/wiFred

- [[[JMRI]]] JMRI: A Java Model Railroad Interface, https://www.jmri.org

- [[[jmrihardwaresupport,Supported Hardware]]] JMRI: Hardware Support, https://www.jmri.org/help/en/html/hardware/index.shtml

- [[[wiThrottleApp,wiThrottle]]] WiThrottle, https://www.withrottle.com/html/home.html

- [[[EngineDriver]]] Home | EngineDriver, https://enginedriver.mstevetodd.com/

- [[[Fremo]]] Home - FREMO - Freundeskreis Europäischer Modelleisenbahner e.V., https://www.fremo-net.eu/

- [[[FRED]]] FRED, http://fremodcc.sourceforge.net/diy/fred/fred_d.html

- [[[FREDI]]] FREDI, http://fremodcc.sourceforge.net/diy/fred2/fredi_d.html

- [[[Uhlenbrock]]] Uhlenbrock | FRED, der Handregler für die Intellibox, https://uhlenbrock.de/de_DE/produkte/prodarch/I62AD172-001.htm!ArcEntryInfo=0004.41.I62AD172

- [[[Digitrax,Digitrax LNWI]]] LocoNet WiFi interface, https://www.digitrax.com/products/wireless/lnwi/

- [[[MRC,MRC Prodigy WiFi]]] Prodigy WiFi, https://www.modelrectifier.com/Prodigy-WiFi-s/332.htm

- [[[rpiImage,Steve Todd]]] JMRI RaspberryPi as Access Point | M Steve Todd, https://mstevetodd.com/rpi

- [[[wiClock]]] wiClock, a WiFi-JMRI-Clock, zu finden unter https://github.com/newHeiko/WiFi-JMRI-Clock und Dokumentation unter https://newHeiko.github.io/WiFi-JMRI-Clock