= Background and history of wiFred development
Heiko Rosemann
include::version_en.adoc[]
:description: How the wiFred came to life, background, similar projects
:url-repo: https://github.com/newHeiko/wiFred
:icons: image
:iconsdir: images/icons/
:imagesdir: images/
:toc:

// tag::largefile[]
[#background]
== Background for wiFred development

As of the writing of this document, <<JMRI>> has a long track record of offering a server for using smartphones as wireless model railroad throttles, along with apps like <<wiThrottleApp>>footnote:[wiThrottle is also the name JMRI uses for the protocol and the server.] and <<EngineDriver>>. This server will enable WiFi throttles to control locos any model railroading layout to which JMRI can build a connection <<jmrihardwaresupport>>. In addition, <<Digitrax>> and <<MRC>> offer specific hardware solutions to enable the connection of the abovementioned smartphone apps to their DCC systems through a WiFi network.

The <<Fremo>> is a European modular model railroading club whose unique requirements on its DCC throttles led to the creation of the throttles <<FRED>> and <<FREDI>> - a series of LocoNet-throttles which started their life as hobbyist projects with large numbers in circulation but were also commercially available from <<Uhlenbrock>>.

== Specification wishlist

In modular railroading events, particularly of the Fremo-americaN-group, multiple people have evaluated the smartphone throttle solutions and found them lacking a nice, haptical feedback. But the idea of wireless control without locking into a specific vendor and their necessarily expensive equipment found great approval. So a wishlist was compiled to define the requirements for a wireless throttle:

- Same form factor as the <<FRED>> with similar controls

- Option to control at least two, better four locomotives for double/triple traction (similar to the double FRED)

- Battery runtime of at least six hours

- Exchangeable batteries, so when the battery runs down, they can be quickly exchanged for a charged set or cheap primary cells

- Easy configuration, but not too easy to prevent operators from accidentally selecting other locomotives

- As little change to the existing Fremo Loconet network as possible

- Use of wiThrottle protocol, so the server side of the communication can be assumed to work and does not have to be developed as well

== Development history

The first prototype versions of the wiFred were built to run from two AA cells, either dry batteries or rechargeable NiMH cells. As described in <<oldThrottle>> this required some special adaptations of the housing to fit all components. Even then, experience with the prototypes showed the battery compartment cover did not really fit and easily broke when trying to open and close the battery compartment.

So the next versions were built around an integrated lithium battery, losing the ability to exchange empty batteries, but with increased runtime and proper fit into the housing. Recharging of the second generation is done through a Micro USB connector, so a powerbank can extend the runtime of the device when the internal battery is exhausted. Also, the loco selection switches act as more of a power switch than they did with the first prototypes, reducing power consumption to a negligible amount when all locos are deselected.

The latest prototype will switch from a double processor implementation to a single, new ESP32-S2 processor, saving space, reducing the number of components, placing all SMD components on one side of the PCB and enabling direct USB firmware download. It will not contain any new features over the earlier LiPo battery versions, but mainly be easier to build for the hobbyist.

== Wireless clock

During the development of this wiFred another topic came up in the americaN group of the Fremo, namely wireless clocks with adjustable clock rate for Timetable & Trainorder operations. This led to the spinoff of the <<wiClock>> project.

// end::largefile[]

include::biblio_en.adoc[]