= Quick instructions for wiFred
Heiko Rosemann
2019-11-16
:toc:
:imagesdir: images/

== Finish assembly

. Use drilling jig to drill holes into housing
. Make cutout for micro USB connector
. Use PCB to drill holes for LEDs next to micro USB connector (D101, D102)
. Install LEDs -- long pin (positive) into square pad
  - Red LEDs at D101 and D301 with 3mm spacers
  - Green LEDs at D102, D302 and D303 with 3mm spacers
  - White LEDs at D304 and D305 -- you can choose if you want them on top or bottom and how long they should stick out of housing
. Install potentiometer and loco selection switches
. Install direction selection switch and connect pins to PCB with short wires or cutoffs from LEDs
. Make cut-outs in housing fit all the assembled parts
. Connect battery to P101 - BATT-connector
. Arrange battery so it fits between direction selection switch and PCB screws and glue into back housing

WARNING: Make sure red wire is connected to + and black wire connected to GND. Reversing the connection may destroy the wiFred.

WARNING: Make sure nothing pinches the battery. LiIon batteries are susceptible to mechanical damage.

== First startup

. Charge device with a micro USB charger until charging LED switches to green
. Turn on device with charger still connected (calibrates low battery threshold)
. Wait for red LED on top to stop flashing and stay lit
. Use any WiFi device to search for and connect to network wiFred-configXXXX
. Connect to http://config.local and configure device

More information can be found at https://newHeiko.github.io/wiFred.